export const API_KEY_EXPIRATION_SWITCH = "API_KEY_EXPIRATION_SWITCH"
export const API_KEY_EXPIRATION_PICKER_INPUT = "API_KEY_EXPIRATION_PICKER_INPUT"
export const UPDATE_PROFILE_LANGUAGE_SELECT = "UPDATE_PROFILE_LANGUAGE_SELECT"